### ISSUE TITLE
Serial only?

### ISSUE THREAD

**Issue by hazcod** [SteinHeselmans/DucoBox#29]
Hey Stein, bedankt voor jouw werk! Ik denk eraan dit te porten naar Javascript voor homebridge.
Gebeurt de communicatie met Duco enkel via seriepoort? (e.g. geen http api of dergelijke)

**Comment by SteinHeselmans** [comment]
voor zover ik weet is de duco een vrij simpele box, ik heb op de printplaat geen wifi/eth aansluitingen gezien. Ik gebruik een raspi als bridge naar een ethernet/wifi netwerk.
